### ISSUE TITLE
Fix the UI issue: bottom navigation drawer covers the bottom portion of the fragment

### ISSUE THREAD

**Issue by dambadipudi** [dynamite8/resources-android-dev#53]

**Comment by oa2013** [comment]
@dambadipudi Okay, I will look at this in the few days and will push a fix.

**Comment by dnisharar** [comment]
Tried to run the project from Grow with google scholarship but it has 18 error. Sad.

**Comment by JaeW** [comment]
I'm sorry @dnisharar, who are you?
