### ISSUE TITLE
Create method to populate Room db with mock data

### ISSUE THREAD

**Issue by JaeW** [dynamite8/resources-android-dev#62]

**Comment by JaeW** [comment]
@ijeomaezeonyebuchi Here is the article about and the code repo on pre-populating the db.

7 Pro Tips for Room
https://medium.com/google-developers/7-pro-tips-for-room-fbadea4bfbd1

https://gist.github.com/florina-muntenescu/697e543652b03d3d2a06703f5d6b44b5

**Comment by JaeW** [comment]
Here's another reference since sometimes it helps to have multiple.
https://android.jlelse.eu/pre-populate-room-database-6920f9acc870

**Comment by BlitheBrandon** [comment]
If you need to create mock data, this StackOverflow question/answer has some tools listed.
https://stackoverflow.com/questions/591892/tools-for-generating-mock-data
