### ISSUE TITLE
Create CustomView comprised of note image and overlying TextView

### ISSUE THREAD

**Issue by JaeW** [dynamite8/resources-android-dev#70]
On main screen, each topic item is displayed on top of a sticky note image.  Currently each note is placed individually within a ConstraintLayout along with an overlaid TextView.  

If these two components are combined into a CustomView, the main screen can contain a RecyclerView with a GridLayout with each grid containing a topic item.

**Comment by oa2013** [comment]
The pending PR creates a CustomView.

**Comment by dambadipudi** [comment]
Is CustomView different from what was taught in the course? Like in our sunshine app, you could create a sticky_note_view.xml layout file as a single item in the RecyclerView with the fragment_home being a GridLayout containing each item.

Any reason for not using RecyclerView for displaying them?

**Comment by JaeW** [comment]
@dambadipudi The course did not teach anything about CustomViews.  The difference between what was done in the Sunshine app and an Android CustomView is this:  In Sunshine you create a different _layout_ (which when discussing architecture patterns is known as the view).  So you're modifying the look of the UI but still uses stock (or supplemental) Android object/components.  With a CustomView you either combine or add custom behaviors and attributes to a particular view object by extending the View class (but you can also extend a View subclass such as a ButtonView).  

If you have the Spotify app there is a great example there.  When you hit the search option on the bottom tab, an EditText view appears at the top.  But if you notice, there is _also_ a camera icon on the right-hand side of that EditText which, when clicked, launches Spotify Codes functionality.  In order to get that behavior, they have bundled several View objects (ImageButton, EditText at the very least) into a new CustomView class.  The advantage is its reusability as well as the ability to abstract the custom behavior away from the app logic into a separate class (where it can expose only the behaviors you choose and make how it does what it does inconsequential). 

Here is a tutorial for creating a CustomView from two View subclasses.  Do note that one can also extend the View class directly, but doing that is _far_ more complex as you have to deal with the drawing/ on-screen rendering in addition to behavior.

https://www.intertech.com/Blog/android-custom-view-tutorial-part-1-combining-existing-views/

**Comment by JaeW** [comment]
@dambadipudi Another thought.  Another advantage to doing it this way is that automated testing can be done on it separate from the testing done on app logic and behavior.
